import * as webllm from "https://esm.run/@mlc-ai/web-llm";

const LIGHT_MODEL = "Qwen2-0.5B-Instruct-q4f16_1-MLC";
const STRONG_MODEL = "Llama-3.2-1B-Instruct-q4f16_1-MLC";
const DEFAULT_MODEL = LIGHT_MODEL;
const STORAGE_KEY = "manifest-chat-v1";
const SYSTEM_PROMPT = `You are Manifest, a thoughtful and capable AI assistant running locally in the user's browser. Be clear, useful, concise when possible, and candid about uncertainty. Do not claim access to the internet, private files, accounts, or tools unless the user has actually provided the relevant information in the conversation.`;
const $ = id => document.getElementById(id);
const els = {sidebar:$("sidebar"),scrim:$("scrim"),menuBtn:$("menuBtn"),newChatBtn:$("newChatBtn"),newChatDemoBtn:$("newChatDemoBtn"),clearBtn:$("clearBtn"),aboutBtn:$("aboutBtn"),settingsBtn:$("settingsBtn"),settingsModal:$("settingsModal"),aboutModal:$("aboutModal"),deviceModal:$("deviceModal"),deviceModalClose:$("deviceModalClose"),analyzeAgainBtn:$("analyzeAgainBtn"),loadModelBtn:$("loadModelBtn"),loadNote:$("loadNote"),statusPill:$("statusPill"),progressWrap:$("progressWrap"),progressText:$("progressText"),progressBar:$("progressBar"),composer:$("composer"),promptInput:$("promptInput"),sendBtn:$("sendBtn"),messages:$("messages"),welcome:$("welcome"),chatStage:$("chatStage"),scanState:$("scanState"),deviceName:$("deviceName"),capacityScore:$("capacityScore"),capacityBar:$("capacityBar"),capacityLabel:$("capacityLabel"),specPlatform:$("specPlatform"),specCores:$("specCores"),specMemory:$("specMemory"),specWebGPU:$("specWebGPU"),specGPU:$("specGPU"),specBuffer:$("specBuffer"),recommendedTier:$("recommendedTier"),recommendedReason:$("recommendedReason"),useRecommendedBtn:$("useRecommendedBtn")};
let engine=null,loading=false,generating=false,recommendedModel=null;
let selectedModel=localStorage.getItem("manifest-model")||DEFAULT_MODEL;
let modelChosen=false;
let history=loadHistory();
function loadHistory(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");return Array.isArray(p)?p.filter(m=>["user","assistant"].includes(m.role)&&typeof m.content==="string"):[]}catch{return[]}}
function saveHistory(){localStorage.setItem(STORAGE_KEY,JSON.stringify(history.slice(-30)))}
function escapeHTML(v=""){return v.replace(/[&<>'\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"}[c]))}
function simpleMarkdown(t=""){let s=escapeHTML(t);return s.replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").split(/\n{2,}/).map(b=>`<p>${b.replace(/\n/g,"<br>")}</p>`).join("")}
function scrollToBottom(){requestAnimationFrame(()=>{if(els.chatStage)els.chatStage.scrollTop=els.chatStage.scrollHeight;else if(els.messages)els.messages.scrollTop=els.messages.scrollHeight})}
function updateWelcome(){els.welcome.classList.toggle("hidden",history.length>0);els.messages.classList.toggle("hidden",history.length===0)}
function renderHistory(){els.messages.innerHTML="";history.forEach(m=>addMessageNode(m.role,m.content));updateWelcome();scrollToBottom()}
function addMessageNode(role,content,extraClass=""){const row=document.createElement("div");row.className=`message ${role} ${extraClass}`.trim();if(role==="assistant"){const a=document.createElement("div");a.className="message-avatar";a.textContent="M";row.appendChild(a)}const body=document.createElement("div");body.className="message-body";body.innerHTML=simpleMarkdown(content);row.appendChild(body);els.messages.appendChild(row);updateWelcome();scrollToBottom();return{row,body}}
function setStatus(text,ready=false){els.statusPill.textContent=text;els.statusPill.classList.toggle("ready",ready)}
function setProgress(r){els.progressWrap.classList.remove("hidden");els.progressText.textContent=r?.text||"Preparing model…";const n=typeof r?.progress==="number"?r.progress:null;els.progressBar.style.width=n==null?"8%":`${Math.max(3,Math.min(100,n*100))}%`}
function syncModelUI(){const i=document.querySelector(`input[name="model"][value="${CSS.escape(selectedModel)}"]`);if(i)i.checked=true}
function formatBytes(n){if(!n)return"Browser default";return n>=1073741824?`${(n/1073741824).toFixed(1)} GB`:`${Math.round(n/1048576)} MB`}
function platformName(){const ua=navigator.userAgent;return /Android/i.test(ua)?"Android":/iPhone|iPad|iPod/i.test(ua)?"iOS / iPadOS":/Windows/i.test(ua)?"Windows":/Macintosh|Mac OS/i.test(ua)?"macOS":/Linux/i.test(ua)?"Linux":"Browser device"}
function openAnalysis(){if(!els.deviceModal.open)els.deviceModal.showModal();analyzeDevice()}
async function analyzeDevice(){els.scanState.classList.add("active");els.scanState.innerHTML="<i></i> Analyzing";els.recommendedTier.textContent="Analyzing…";els.recommendedReason.textContent="Manifest is reading the hardware capabilities this browser safely exposes.";const cores=navigator.hardwareConcurrency||null;const memory=navigator.deviceMemory||null;let adapter=null,info=null,maxBuffer=0;try{if(navigator.gpu){adapter=await navigator.gpu.requestAdapter({powerPreference:"high-performance"});if(adapter){info=adapter.info||null;maxBuffer=Number(adapter.limits?.maxBufferSize||0)}}}catch(e){console.warn("Device analysis WebGPU query failed",e)}
const webgpu=!!adapter;let score=15;if(webgpu)score+=35;if(cores)score+=Math.min(20,cores*2);if(memory)score+=Math.min(20,memory*2.5);if(maxBuffer>=1073741824)score+=10;else if(maxBuffer>=536870912)score+=6;score=Math.min(100,Math.round(score));const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);const stronger=webgpu&&!mobile&&(memory==null||memory>=8)&&(cores==null||cores>=6);recommendedModel=stronger?STRONG_MODEL:LIGHT_MODEL;const gpuLabel=[info?.vendor,info?.architecture].filter(Boolean).join(" / ")||(webgpu?"WebGPU adapter available":"Not exposed");els.deviceName.textContent=mobile?"Mobile device":"Desktop / Laptop";els.specPlatform.textContent=platformName();els.specCores.textContent=cores?String(cores):"Not exposed";els.specMemory.textContent=memory?`~${memory} GB reported`:"Not exposed";els.specWebGPU.textContent=webgpu?"Available":"Unavailable";els.specGPU.textContent=gpuLabel;els.specBuffer.textContent=webgpu?formatBytes(maxBuffer):"—";els.capacityScore.textContent=`${score} / 100`;els.capacityBar.style.width=`${score}%`;els.capacityLabel.textContent=webgpu?"Browser-local accelerated AI is available on this device.":"This browser does not currently expose WebGPU, so local GPU inference is unavailable here.";els.recommendedTier.textContent=stronger?"Llama 3.2 1B":"Qwen2 0.5B";els.recommendedReason.textContent=stronger?"Your exposed browser capabilities support trying the stronger model in this prototype.":webgpu?"Manifest recommends the lighter model for a more reliable local experience on this device.":"WebGPU is required for the current browser-local prototype.";els.useRecommendedBtn.disabled=!webgpu;els.scanState.innerHTML="<i></i> Analysis complete";localStorage.setItem("manifest-device-score",String(score))}
async function applyRecommended(){if(!recommendedModel)return;selectedModel=recommendedModel;modelChosen=true;localStorage.setItem("manifest-model",selectedModel);if(engine){try{await engine.unload()}catch{}engine=null}syncModelUI();setStatus("Recommended");els.deviceModal.close();els.loadModelBtn.textContent="Load Recommended Model";els.loadNote.textContent="Manifest selected the recommended model for this device. Load it to start chatting."}
async function loadModel(){if(loading||generating)return false;if(!navigator.gpu){setStatus("WebGPU unavailable");els.loadNote.textContent="This browser/device does not expose WebGPU.";return false}loading=true;els.loadModelBtn.disabled=true;els.sendBtn.disabled=true;setStatus("Loading…");setProgress({text:"Starting local AI engine…",progress:.01});try{engine=await webllm.CreateMLCEngine(selectedModel,{initProgressCallback:setProgress});modelChosen=true;setStatus("Ready",true);els.loadModelBtn.textContent="Model ready";els.loadNote.textContent="Loaded locally. You can start chatting.";els.progressWrap.classList.add("hidden");els.sendBtn.disabled=!els.promptInput.value.trim();return true}catch(e){console.error(e);engine=null;setStatus("Load failed");els.loadModelBtn.disabled=false;els.loadModelBtn.textContent="Try loading again";els.loadNote.textContent="The model could not load on this device. Try the Light model.";return false}finally{loading=false}}
async function sendMessage(text){const prompt=text.trim();if(!prompt||generating)return;if(!engine){els.promptInput.value=prompt;if(!modelChosen){openAnalysis();return}const loaded=await loadModel();if(!loaded)return}generating=true;els.promptInput.value="";autoResize();history.push({role:"user",content:prompt});saveHistory();addMessageNode("user",prompt);const node=addMessageNode("assistant","Thinking…","thinking");let answer="";try{const stream=await engine.chat.completions.create({messages:[{role:"system",content:SYSTEM_PROMPT},...history.slice(-18)],temperature:.7,top_p:.9,max_tokens:700,stream:true});node.row.classList.remove("thinking");for await(const chunk of stream){answer+=chunk?.choices?.[0]?.delta?.content||"";node.body.innerHTML=simpleMarkdown(answer);scrollToBottom()}if(!answer.trim())answer="I wasn't able to generate a response.";node.body.innerHTML=simpleMarkdown(answer);history.push({role:"assistant",content:answer});saveHistory()}catch(e){console.error(e);node.row.classList.remove("thinking");node.body.innerHTML=simpleMarkdown("I hit a local inference error on this device. Please try again.")}finally{generating=false;autoResize()}}
function resetConversation(){history=[];saveHistory();renderHistory();els.promptInput.value="";autoResize()}
function autoResize(){els.promptInput.style.height="auto";els.promptInput.style.height=`${Math.min(160,els.promptInput.scrollHeight)}px`;els.sendBtn.disabled=generating||loading||!els.promptInput.value.trim()}
els.loadModelBtn.addEventListener("click",async()=>{if(!modelChosen){openAnalysis();return}if(!engine)await loadModel()});els.deviceModalClose?.addEventListener("click",()=>els.deviceModal.close());els.analyzeAgainBtn?.addEventListener("click",analyzeDevice);els.useRecommendedBtn?.addEventListener("click",applyRecommended);els.composer.addEventListener("submit",e=>{e.preventDefault();sendMessage(els.promptInput.value)});els.promptInput.addEventListener("input",autoResize);els.promptInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();els.composer.requestSubmit()}});document.querySelectorAll(".suggestion").forEach(b=>b.addEventListener("click",()=>sendMessage(b.dataset.prompt||"")));els.newChatBtn?.addEventListener("click",resetConversation);els.newChatDemoBtn?.addEventListener("click",resetConversation);els.clearBtn?.addEventListener("click",resetConversation);els.settingsBtn.addEventListener("click",()=>{syncModelUI();els.settingsModal.showModal()});document.querySelectorAll('input[name="model"]').forEach(input=>input.addEventListener("change",async()=>{selectedModel=input.value;modelChosen=true;localStorage.setItem("manifest-model",selectedModel);if(engine){try{await engine.unload()}catch{}engine=null}setStatus("Not loaded");els.loadModelBtn.disabled=false;els.loadModelBtn.textContent="Load Selected Model";els.loadNote.textContent="Model selected manually. Load it to begin chatting."}));syncModelUI();renderHistory();autoResize();